<?php

/**
 * Template name: Empresas do Grupo
 *
 */

get_header(); ?>

<div class="container">
	<div class="row">

		<!-- <div data-aos="zoom-out-right">teste</div> -->
		<style>
			/* .dropdown {
				overflow: hidden;
			} */
			.favo {
				width: 32px;
				z-index: 99;
				transition: 1s all;
			}

			.favo-anim:hover {
				transform: rotate(180deg) scale(1.15) !important;
			}

			.favo-anim {
				transform: rotate(180deg) scale(1.15) !important;
				transition: 1s all;
			}

			.favo-text {
				color: #d0810b !important;
				font-weight: 800;
				padding: 0 15px;
				overflow: hidden;
			}

			.hid-cont {
				display: none;
			}

			.bg-sblue {
				background-color: var(--bg-sblue);
			}

			.expand-menu {
				animation-name: Expand1;
				/* animation-duration: 2s; */
				transition: 1s all;
				animation-fill-mode: forwards;
			}

			.close-menu {
				animation-name: fechar;
				/* animation-duration: 2s; */
				transition: 2s all;
				animation-fill-mode: forwards;
			}

			@keyframes Expand1 {
				0% {
					height: 0;
				}

				100% {
					height: 100vh;
				}
			}

			@keyframes fechar {
				0% {
					height: 100vh;
				}

				100% {
					height: 0;
				}
			}

			@keyframes movingL {
				0% {
					left: -200px;
					top: 0;
				}

				50% {
					left: -220px;
					top: 15px;

				}

				100% {
					left: -200px;
					top: 0;

				}
			}

			.o-hidden {
				overflow: hidden;
			}

			.bg-bee-grey-left {
				position: absolute;
				height: 0;
				left: -200px;
				top: 0;
				opacity: 0.1;
			}

			.bg-bee-grey-right {
				position: absolute;
				height: 0;
				right: -100px;
				bottom: 350px;
				opacity: 0.1;
				-moz-transform: scaleX(-1);
				-o-transform: scaleX(-1);
				-webkit-transform: scaleX(-1);
				transform: scaleX(-1);
			}

			@media screen and (max-width: 768px) {

				.bg-bee-grey-right,
				.bg-bee-grey-left {
					display: none;
				}
			}

			.content {
				position: inherit;
				z-index: 2;
			}
		</style>

		<!-- Image Map Generated by http://www.image-map.net/ -->

		<map name="image-map">
			<area target="" alt="Dipro" title="Dipro" href="#dipro" coords="57,322,19,253,57,186,138,185,177,253,137,321" shape="poly">
			<area target="" alt="Cobreflex" title="Cobreflex" href="#cobreflex" coords="146,178,184,109,264,111,300,178,263,242,186,246" shape="poly">
			<area target="" alt="Conduspar" title="Conduspar" href="#conduspar" coords="309,171,270,105,309,35,387,37,426,105,388,172" shape="poly">
			<area target="" alt="Integra" title="Integra" href="#integra" coords="60,467,21,397,59,329,138,334,174,398,140,464" shape="poly">
			<area target="" alt="Area" title="Area" href="#area" coords="148,324,186,260,264,257,301,325,263,390,185,394" shape="poly">
			<area target="" alt="Norphel" title="Norphel" href="#norphel" coords="310,317,273,249,311,181,388,184,426,250,389,314" shape="poly">
		</map>

		<?php get_template_part('content', 'menu'); ?>

		<section>
			<div class="container position-relative">
				<div class="row mt-4 justify-content-center align-items-center content">
					<div class="col-12">
						<h5 class="laranja-global text-center">QUEM SOMOS</h5>
						<h3 class="text-center text-uppercase"><?= get_the_title() ?></h3>
					</div>
					<div class="col-12 col-md-6 text-center mt-3">
						<img usemap="#image-map" src="<?php echo get_stylesheet_directory_uri() . '/assets/images/' ?>colmeia.png" alt="" srcset="">
					</div>
					<div class="col-12 col-md-6 text-center">
						<h3 class="laranja-global mb-4">COBREFLEX</h3>
						<img class="w-75 rounded-5" src="<?php echo get_stylesheet_directory_uri() . '/assets/images/' ?>cobreflex.png" alt="" srcset="">
						<p class="mt-3">Já a COBREFLEX, nossa Industria de fios e cabos de baixa tensão, em Jandira São Paulo, produz condutores elétricos de altíssima qualidade que são certificados por empresas idôneas.</p>
						<button type="button" class="btn btn-warning fw-bold text-gray">Veja mais</button>

					</div>
				</div>
				<div class="bg-bee-grey-left">
					<img src="<?php echo get_stylesheet_directory_uri() . '/assets/images/' ?>bg-bee-removebg-preview.png" alt="" srcset="">
				</div>
				<div class="bg-bee-grey-right">
					<img src="<?php echo get_stylesheet_directory_uri() . '/assets/images/' ?>bg-bee-removebg-preview.png" alt="" srcset="">
				</div>
			</div>
		</section>

		<script>
			areas = document.querySelectorAll('area');

			areas.forEach((x) => {
				x.addEventListener('click', () => {
					document.querySelector("body > div.container > div > section:nth-child(4) > div > div.row.mt-4.justify-content-center.align-items-center.content > div:nth-child(1) > h5").innerHTML = 'funcionando'
				})
			})
		</script>

		<script>
			const favos = document.querySelectorAll('.favo');
			const favosText = document.querySelectorAll('.favo-text');
			const spacing = document.querySelectorAll('.dropdown');
			const menu = document.querySelector('.hid-menu');
			const menuAnim = document.querySelector('.fav-roll-close')

			// MOSTRAR MENU
			document.querySelector('.abrir').addEventListener('click', () => {
				menu.classList.toggle('expand-menu');
				menu.classList.toggle('close-menu');
			})

			menuAnim.addEventListener('click', () => {
				menuAnim.classList.toggle('fav-roll-close');
				menuAnim.classList.toggle('fav-roll-open')
				favos.forEach((x) => {
					x.click()
				})
				document.querySelector('body').classList.toggle('o-hidden')
				window.scrollTo(0, 0);

			})

			// APARECER TEXTO AO LADO DOS FAVOS
			favos.forEach((x, y) => {
				x.addEventListener('mouseover', () => {
					favosText[y].classList.remove('hid-cont');
					favosText[y].classList.add('animate__fadeInRight', 'animate__animated')
					x.classList.remove('animate__fadeInDown', 'animate__animated', 'animate__delay-' + i + 's');
					setTimeout(() => {
						x.classList.add('favo-anim');
					}, 100)
				})
				x.addEventListener('click', () => {
					favosText[y].classList.remove('hid-cont');
					favosText[y].classList.toggle('animate__fadeInRight')
					favosText[y].classList.toggle('animate__animated')
					// x.classList.toggle('animate__fadeInDown', 'animate__animated', 'animate__delay-' + i + 's');
					// setTimeout(() => {
					// 	x.classList.add('favo-anim');
					// }, 100)
				})
			})

			// APARECER FAVOS
			setTimeout(() => {
				i = 1;
				favos.forEach((x, y) => {
					x.classList.remove('hid-cont');
					x.classList.add('animate__fadeInDown', 'animate__animated', 'animate__delay-' + 1 + 's');
					i++;
				})

			}, 0)

			// setTimeout(()=>{
			// 	i = 1;
			// 	favos.forEach((x,y) => {
			// 	// x.classList.remove('hid-cont');
			// 	x.classList.remove('animate__fadeInDown', 'animate__animated','animate__delay-'+i+'s');
			// 	i++;
			// })

			// }, 4800)




			spacing.forEach((x) => {
				// margem noas listas dos favos
				let fix = 20;
				let mv = fix;
				el = x.children[1].children.length;
				for (let i = 0; i < el; i++) {
					x.children[1].children[i].style.marginLeft = mv + 'px';
					mv = mv + fix;
				}
			})
		</script>
	</div><!-- .row -->
</div><!-- #wrapper -->

<?php
get_footer();
